# name: Pre-commit checks

# on:
#   push:
#     branches: ['main']

# jobs:
#   pre-commit:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '18'

#       - name: Install dependencies
#         run: npm install

#       - name: Run linters
#         run: npm run lint

#       - name: Install Chrome dependencies
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y \
#             libappindicator3-1 \
#             fonts-liberation \
#             libasound2 \
#             libatk-bridge2.0-0 \
#             libatk1.0-0 \
#             libcups2 \
#             libdbus-glib-1-2 \
#             libxcomposite1 \
#             libxrandr2 \
#             xdg-utils \
#             libgbm1 \
#             libnss3 \
#             libxss1 \
#             libxtst6 \
#             libgtk-3-0 \
#             libnotify4 \
#             libgconf-2-4 \
#             libxi6 \
#             libxss1

#       - name: start chrome
#         run:
#           chromium-browser --headless --no-sandbox --disable-gpu --disable-dev-shm-usage --remote-debugging-port=9222 --user-data-dir=/tmp/chrome-profile &
#           sleep 5 # Wait a few seconds to allow Chrome to start

#       - uses: nanasess/setup-chromedriver@v2
#         with:
#           # Optional: do not specify to match Chrome's version
#           # chromedriver-version: '88.0.4324.96'
#           chromedriver-version: '116.0'
#       - run: |
#           export DISPLAY=:99
#           chromedriver --port=9515 --url-base=/wd/hub &
#           sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

#       - name: Set permissions for Chrome
#         run: |
#           sudo chmod +x /usr/bin/google-chrome
#           sudo chmod +x /usr/bin/chromium

#       - name: Check active ports
#         run: lsof -i -P -n | grep LISTEN

#       - name: Run GUI tests
#         run: npm run start:test & # Start the server in the background

#       - name: Shutdown Chrome
#         run: |
#           pkill -f chromium-browser || true # Use pkill to gracefully kill the browser

#       # - name: Check formatting
#       #   run: npm run format-check

name: Pre-commit checks

on:
  push:
    branches: ['main']

jobs:
  pre-commit:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install Google Chrome
        run: choco install googlechrome -y

      - name: Install Chromedriver
        run: choco install chromedriver -y

      - name: Start Chrome and Chromedriver
        run: |
          $chromedriverPath = Get-Command chromedriver | Select-Object -ExpandProperty Source
          Write-Host "Chromedriver is located at: $chromedriverPath"

          Start-Process "C:\Program Files\Google\Chrome\Application\chrome.exe" -ArgumentList "--headless", "--no-sandbox", "--disable-gpu", "--disable-dev-shm-usage", "--remote-debugging-port=9222", "--user-data-dir=$env:TEMP\chrome-profile"
          Start-Sleep -Seconds 5 # Wait a few seconds for Chrome to start

          Start-Process "$chromedriverPath" -ArgumentList "--port=9515", "--verbose"
          Start-Sleep -Seconds 5 # Wait for Chromedriver to start

      - name: Check if Chrome is running
        run: |
          netstat -ano | findstr LISTENING | findstr 9515 || { echo "Chromedriver is not listening on port 9515"; exit 1; }

      - name: Check if Chrome is running
        run: |
          netstat -ano | findstr LISTENING | findstr 9515

      - name: Run tests
        run: |
          # npx wait-on http://localhost:5173 || { echo "Server failed to start"; exit 1; }
          npm run test || { echo "Tests failed"; exit 1; }

      - name: Shutdown Chrome and ChromeDriver
        run: |
          Stop-Process -Name chrome -Force
          Stop-Process -Name chromedriver -Force
