name: Pre-commit checks

on:
  push:
    branches: ['main']

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        ports:
          - '4444:4444'
          - '7900:7900'
        options: --shm-size=2gb

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      - name : docker start Selenium
        run: docker run -d -p 4444:4444 -p 7900:7900 --shm-size="2g" selenium/standalone-chrome:latest

      - name: Wait for Selenium to be ready
        run: |
          echo "Waiting for Selenium to be ready..."
          until curl -s http://localhost:4444/ | grep -q '"ready":true'; do
            sleep 5
          done

      - name: Run GUI tests
        run: npm run start:test # Adjust according to your test command


      # - name: Check formatting
      #   run: npm run format-check
