name: Pre-commit checks

on:
  push:
    branches: ['main']

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint

      # - name: Build Dev
      #   run: npm run dev

      # - name: Run tests
      #   run: npm run test

      # - name: Run tests
      #   run: npm run test

      # - name: Check formatting
      #   run: npm run format-check
