name: Pre-commit checks

on:
  push:
    branches: ['main']

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    # services:
    #   selenium:
    #     image: seleniarm/standalone-chromium:116.0-chromedriver-116.0-grid-4.10.0-20230828
    #     ports:
    #       - '4444:4444'
    #       - '7900:7900'
    #     options: --shm-size=2gb

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint
              
      # - uses: browser-actions/setup-chrome@latest
      # - run: chrome --version
      - uses: nanasess/setup-chromedriver@v2
        with:
          # Optional: do not specify to match Chrome's version
          chromedriver-version: '88.0.4324.96'
          options: |
            {
              "browser": "chrome",
              "enableVNC": true,
              "enableVideo": false,
              "browserVersion": "latest",
              "selenoid": {
                "chromeOptions": {
                  "args": [
                    "--no-sandbox",
                    "--disable-dev-shm-usage"
                  ]
                }
              }
            }
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      # - name: Start selenoid
      #   uses: Xotabu4/selenoid-github-action@v2

      # - name: Wait for Selenium to be ready
      #   run: |
      #     echo "Waiting for Selenium to be ready..."
      #     until curl -s http://localhost:4444/wd/hub | grep -q '"ready":true'; do
      #       sleep 5
      #     done

      - name: Run GUI tests
        run: npm run start:test # Adjust according to your test command


      # - name: Check formatting
      #   run: npm run format-check
